### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by trafoziya** [LlamaLad7/MixinExtras#36]
Hey, so I have an issue which I start my instance in MultiMC. Its OK until here right, then it crashes. I was looking through the crash logs for something like 1.5 hours trying to understand what is going on because every time I try to start the instance, the reason seems to change. It connects to almost half of my mods, though only thing that does not change is you and your package **com.llamalad7.mixinextras**. I need some help and i would really appreciate it if you would.

Here are my logs:

```
MultiMC version: 0.7.0-3775


Launched instance in online mode

authserver.mojang.com resolves to:
    [13.32.110.84, 13.32.110.119, 13.32.110.82, 13.32.110.97]

session.minecraft.net resolves to:
    [13.107.213.45, 13.107.246.45]

textures.minecraft.net resolves to:
    [13.107.213.45, 13.107.246.45]

api.mojang.com resolves to:
    [13.107.246.45, 13.107.213.45]


Minecraft folder is:
C:/Users/omerz/OneDrive/Masaüstü/MultiMC/instances/1.18.2/.minecraft


Java path is:
C:/Program Files/Java/jdk-20/bin/javaw.exe


Checking Java version...
Java is version 20.0.1, using 64-bit architecture, from Oracle Corporation.


Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/instances/1.18.2/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.17.0/log4j-slf4j18-impl-2.17.0.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/com/mojang/datafixerupper/4.1.27/datafixerupper-4.1.27.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/com/mojang/authlib/3.3.39/authlib-3.3.39.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.17.0/log4j-api-2.17.0.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.17.0/log4j-core-2.17.0.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/com/mojang/text2speech/1.12.4/text2speech-1.12.4.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/cpw/mods/securejarhandler/1.0.8/securejarhandler-1.0.8.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/ow2/asm/asm/9.5/asm-9.5.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/net/minecraftforge/eventbus/5.0.3/eventbus-5.0.3.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/net/minecraftforge/forgespi/4.0.15-4.x/forgespi-4.0.15-4.x.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/net/minecraftforge/coremods/5.0.1/coremods-5.0.1.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/cpw/mods/modlauncher/9.1.3/modlauncher-9.1.3.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/net/minecraftforge/JarJarSelector/0.3.19/JarJarSelector-0.3.19.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/net/minecraftforge/JarJarMetadata/0.3.19/JarJarMetadata-0.3.19.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/cpw/mods/bootstraplauncher/1.0.0/bootstraplauncher-1.0.0.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/net/minecraftforge/JarJarFileSystems/0.3.19/JarJarFileSystems-0.3.19.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/net/minecraftforge/fmlloader/1.18.2-40.2.9/fmlloader-1.18.2-40.2.9.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/com/mojang/minecraft/1.18.2/minecraft-1.18.2-client.jar

Native libraries:
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/com/mojang/text2speech/1.12.4/text2speech-1.12.4-natives-windows.jar

Mods:
  [✔️] additionaladditions-4.0.4.jar
  [✔️] AdvancementPlaques-1.18.2-1.4.5.1.jar
  [✔️] AE2WTLib-11.6.3.jar
  [✔️] AkashicTome-1.5-20.jar
  [✔️] alexsmobs-1.18.6.jar
  [✔️] almostunified-forge-1.18.2-0.3.10.jar
  [✔️] AmbientSounds_FORGE_v5.0.16_mc1.18.2.jar
  [✔️] Annotated-DI-Forge-4.0.3+1.18.2.jar
  [✔️] appliedenergistics2-forge-11.7.4.jar
  [✔️] Applied-Mekanistics-1.2.1.jar
  [✔️] architectury-4.11.93-forge.jar
  [✔️] auto_third_person-forge-1.18.2-2.jar
  [✔️] AutoRegLib-1.7-53.jar
  [✔️] badpackets-forge-0.1.2.jar
  [✔️] balm-3.2.6.jar
  [✔️] beautifiedchatclient-1.18.2-2.2.jar
  [✔️] BetterAnimationsCollection-v3.0.0-1.18.2-Forge.jar
  [✔️] bettercombat-forge-1.6.2+1.18.2.jar
  [✔️] BetterF3-3.0.0-Forge-1.18.2.jar
  [✔️] BetterFurnacesReforged-1.18.2-1.3.2.jar
  [✔️] BetterPingDisplay-1.18.2-1.1.jar
  [✔️] Boat-Item-View-Forge-1.18-0.0.3.jar
  [✔️] Bookshelf-Forge-1.18.2-13.3.56.jar
  [✔️] Botania-1.18.2-435.jar
  [✔️] bwncr-3.13.21.jar
  [✔️] caelus-forge-1.18.1-3.0.0.2.jar
  [✔️] carryon-1.18.2-1.17.1.12.jar
  [✔️] citadel-1.11.3-1.18.2.jar
  [✔️] clienttweaks-forge-1.18.1-7.1.0.jar
  [✔️] cloth-config-6.3.81-forge.jar
  [✔️] Clumps-forge-1.18.2-8.0.0+17.jar
  [✔️] cofh_core-1.18.2-9.2.1.39.jar
  [✔️] collective-1.18.2-6.62.jar
  [✔️] compacthelpcommand-1.18.2-2.3.jar
  [✔️] compressedcreativity-1.18.2-0.1.7.jar
  [✔️] connectedness-1.18.2-2.0.1a.jar
  [✔️] Controlling-forge-1.18.2-9.0+23.jar
  [✔️] CooperativeAdvancements-1.18.2-forge-1.3.0.jar
  [✔️] craftingtweaks-forge-1.18.2-14.0.7.jar
  [✔️] create_central_kitchen-1.18.2-for-create-0.5.1.b-1.3.7.d.jar
  [✔️] create_crystal_clear-0.1.1c.jar
  [✔️] create_enchantment_industry-1.18.2-for-create-0.5.1.b-1.2.5.jar
  [✔️] create_jetpack-1.5.1.jar
  [✔️] create-1.18.2-0.5.1.c.jar
  [✔️] createaddition-1.18.2-20230527a.jar
  [✔️] createappliedkinetics-1.3.jar
  [✔️] createoreexcavation-1.1.1.jar
  [✔️] CreativeCore_FORGE_v2.6.17_mc1.18.2.jar
  [✔️] cryingportals-1.18.2-2.3.jar
  [✔️] CTM-1.18.2-1.1.5+5.jar
  [✔️] ctov-2.9.4.jar
  [✔️] curios-forge-1.18.2-5.0.9.1.jar
  [✔️] curiouselytra-forge-1.18.1-5.0.1.0.jar
  [✔️] darkness-forge-mc118-2.0.91.jar
  [✔️] debugify-1.11.0-forge-1.18.2.jar
  [✔️] DiagonalFences-v3.2.2-1.18.2-Forge.jar
  [✔️] Ding-1.18.2-Forge-1.4.1.jar
  [✔️] doubledoors-1.18.2-5.0.jar
  [✔️] durabilitytooltip-1.1.4-forge-mc1.18.jar
  [✔️] dynamiccrosshair-5.1+1.18.2-forge.jar
  [✔️] eatinganimation-1.18.2-2.1.1.jar
  [✔️] EditSign-1.18.2-2.3.1.jar
  [✔️] EnchantmentDescriptions-Forge-1.18.2-10.0.12.jar
  [✔️] enchlevel-langpatch-2.1.2.jar
  [✔️] entityculling-forge-1.6.1-mc1.18.2.jar
  [✔️] EquipmentCompare-1.18.1-1.2.12.jar
  [✔️] Essential-forge_1-18-2.jar
  [✔️] eureka-1.1.0-beta.9.jar
  [✔️] expandedstorage-8.3.3+1.18.2-forge.jar
  [✔️] ExtraDisks-1.18.2-2.1.0.jar
  [✔️] ExtremeReactors2-1.18.2-2.0.64.jar
  [✔️] extremesoundmuffler-3.30_forge-1.18.2.jar
  [✔️] fancymenu_forge_2.14.7_MC_1.18.2.jar
  [✔️] FarmersDelight-1.18.2-1.2.0.jar
  [✔️] feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2.jar
  [✔️] ferritecore-4.2.2-forge.jar
  [✔️] Fireplace-Lib-Forge-7.0.2+1.18.2.jar
  [✔️] ftbbackups2-forge-1.18.2-1.0.19.jar
  [✔️] ftb-library-forge-1802.3.11-build.177.jar
  [✔️] ftb-quests-forge-1802.3.14-build.191.jar
  [✔️] ftb-teams-forge-1802.2.11-build.107.jar
  [✔️] ftb-ultimine-forge-1802.3.3-build.70.jar
  [✔️] GameMenuModOption-1.18-Forge-1.14.2.jar
  [✔️] geckolib-forge-1.18-3.0.57.jar
  [✔️] grassseeds-1.18.2-3.0.jar
  [✔️] Highlighter-1.18.1-1.1.2.jar
  [✔️] iceandfire-2.1.12-1.18.2.jar
  [✔️] Iceberg-1.18.2-forge-1.0.49.jar
  [✔️] idas_forge-1.6.6+1.18.2.jar
  [✔️] immersive_aircraft-0.4.2+1.18.2-forge.jar
  [✔️] immersive_armors-1.5.5+1.18.2-forge.jar
  [✔️] ImmersiveEngineering-1.18.2-8.4.0-161.jar
  [✔️] ImmersivePosts-1.18.2-4.3.0-3.jar
  [✔️] infernal-expansion-1.18.2-2.5.0.jar
  [✔️] infinitetrading-1.18.2-4.0.jar
  [✔️] integrated_api_forge-1.2.7+1.18.2.jar
  [✔️] integrated_stronghold_forge-1.0.0+1.18.2.jar
  [✔️] InventoryProfilesNext-forge-1.18.2-1.10.6.jar
  [✔️] inventorytotem-1.18.2-3.0.jar
  [✔️] item-filters-forge-1802.2.8-build.50.jar
  [✔️] JRFTL-[1.18.1]-1.3.jar
  [✔️] jumpoverfences-forge-1.18.2-1.0.2.jar
  [✔️] konkrete_forge_1.6.1_MC_1.18-1.18.2.jar
  [✔️] kotlinforforge-3.12.0-all.jar
  [✔️] Ksyxis-Forge1.17-1.1.jar
  [✔️] LegendaryTooltips-1.18.2-1.3.1.jar
  [✔️] libIPN-forge-1.18.2-3.0.2.jar
  [✔️] light-overlay-6.0.5-forge.jar
  [✔️] lightspeed-1.18.2-1.0.2.jar
  [✔️] Mantle-1.18.2-1.9.43.jar
  [✔️] Mekanism-1.18.2-10.2.5.465.jar
  [✔️] MekanismAdditions-1.18.2-10.2.5.465.jar
  [✔️] MekanismGenerators-1.18.2-10.2.5.465.jar
  [✔️] MekanismTools-1.18.2-10.2.5.465.jar
  [✔️] memoryleakfix-forge-1.17+-1.1.1.jar
  [✔️] mob-captains-v2.1.2.jar
  [✔️] modelfix-1.8.jar
  [✔️] MoreBows-1.0.12+1.18.x.forge.jar
  [✔️] MouseTweaks-forge-mc1.18-2.22.jar
  [✔️] naturalist-forge-1.1.1-1.18.2.jar
  [✔️] notenoughanimations-forge-1.6.0-mc1.18.2.jar
  [✔️] notenoughcrashes-4.2.0+1.18.2-forge.jar
  [✔️] oculus-mc1.18.2-1.6.4.jar
  [✔️] open-parties-and-claims-forge-1.18.2-0.19.0.jar
  [✔️] Overlord-Forge-3.2.3+1.18.2.jar
  [✔️] packedup-1.0.29-forge-mc1.18.jar
  [✔️] Patchouli-1.18.2-71.1.jar
  [✔️] Paxi-1.18.2-Forge-2.1.1.jar
  [✔️] plasmovoice-forge-1.18-1.2.19.jar
  [✔️] player-animation-lib-forge-1.0.2+1.18.jar
  [✔️] pneumaticcraft-repressurized-1.18.2-3.6.0-19.jar
  [✔️] polymorph-forge-1.18.2-0.48.jar
  [✔️] Prism-1.18.2-1.0.1.jar
  [✔️] ProjectE-1.18.2-PE1.0.1.jar
  [✔️] projecte-integration-1.18.2-5.4.6.jar
  [✔️] ProjectExpansion-1.18.2-1.0.20.jar
  [✔️] PuzzlesLib-v3.4.6-1.18.2-Forge.jar
  [✔️] Quark-3.2-358.jar
  [✔️] raised-forge-1.18.2-1.2.3.jar
  [✔️] rebind_narrator-forge-1.18.2-2.0.0.jar
  [✔️] Reblured-1.18.2-1.2.0.jar
  [✔️] refinedstorage-1.10.5.jar
  [✔️] refinedstorageaddons-0.8.2.jar
  [✔️] reforgium-1.18.2-1.0.12a.jar
  [✔️] Resourcify (1.18.2-forge)-1.1.0.jar
  [✔️] right-click-harvest-3.2.0+1.18.2-forge.jar
  [✔️] RoughlyEnoughItems-8.3.618.jar
  [✔️] RoughlyEnoughProfessions-forge-1.18.2-1.0.2.jar
  [✔️] screenshot-to-clipboard-1.0.9-forge.jar
  [✔️] selene-1.18.2-1.17.9.jar
  [✔️] simplyswords-forge-1.40-1.18.2.jar
  [✔️] sliceanddice-forge-1.2.1.jar
  [✔️] smoothboot(reloaded)-mc1.18.2-0.0.2.jar
  [✔️] spark-1.10.38-forge.jar
  [✔️] spirit-forge-1.18.2-2.1.8.jar
  [✔️] stackrefill-1.18.2-4.0.jar
  [✔️] starlight-1.0.2+forge.546ae87.jar
  [✔️] supermartijn642configlib-1.1.6-forge-mc1.18.jar
  [✔️] supermartijn642corelib-1.1.10-forge-mc1.18.jar
  [✔️] supplementaries-1.18.2-1.5.18.jar
  [✔️] TaxFreeLevels-1.3.5-forge-1.19.jar
  [✔️] TConstruct-1.18.2-3.6.4.113.jar
  [✔️] teamprojecte-1.18.2-1.1.jar
  [✔️] thermal_cultivation-1.18.2-9.2.0.16.jar
  [✔️] thermal_dynamics-1.18.2-9.2.1b.13.jar
  [✔️] thermal_expansion-1.18.2-9.2.0.20.jar
  [✔️] thermal_foundation-1.18.2-9.2.0.46.jar
  [✔️] thermal_innovation-1.18.2-9.2.0.17.jar
  [✔️] thermal_integration-1.18.2-9.2.0.16.jar
  [✔️] thermal_locomotion-1.18.2-9.2.0.13.jar
  [✔️] tlc_forge-1.0.1-R-1.18.2.jar
  [✔️] toolleveling-forge-1.18.2-1.4.5.jar
  [✔️] ToolSwap-1.18.2-3.1.5.jar
  [✔️] trashcans-1.0.18-forge-mc1.18.jar
  [✔️] TravelersTitles-1.18.2-Forge-2.1.1.jar
  [✔️] Unforgiving-Void-Forge-3.1.5+1.18.2.jar
  [✔️] valkyrienskies-118-2.1.0-beta.12.jar
  [✔️] villagernames-1.18.2-5.2.jar
  [✔️] waveycapes-forge-1.3.2-mc1.18.2.jar
  [✔️] waystone_towers-1.18.2-FORGE-1.0.8.jar
  [✔️] waystones-forge-1.18.2-10.2.1.jar
  [✔️] weaponmaster-1-18-x-multi.jar
  [✔️] wthit-forge-4.13.6.jar
  [✔️] Xaeros_Minimap_23.5.0_Forge_1.18.2.jar
  [✔️] XaerosWorldMap_1.30.6_Forge_1.18.2.jar
  [✔️] YungsApi-1.18.2-Forge-2.2.9.jar
  [✔️] YungsBetterMineshafts-1.18.2-Forge-2.2.jar
  [✔️] YungsBetterNetherFortresses-1.18.2-Forge-1.0.0.jar
  [✔️] YungsBridges-1.18.2-Forge-2.1.0.jar
  [✔️] ZeroCore2-1.18.2-2.1.35.jar

Params:
  --username Tr4fo --version 1.18.2 --gameDir C:/Users/omerz/OneDrive/Masaüstü/MultiMC/instances/1.18.2/.minecraft --assetsDir C:/Users/omerz/OneDrive/Masaüstü/MultiMC/assets --assetIndex 1.18 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userType msa --versionType release --launchTarget forgeclient --fml.forgeVersion 40.2.9 --fml.mcVersion 1.18.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20220404.173914

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms5120m, -Xmx10240m, -Duser.language=en]


Minecraft process ID: 11108


Using onesix launcher.

Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
2023-07-09 00:27:29,471 main WARN Advanced terminal features are not available in this environment
[00:27:29] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Tr4fo, --version, 1.18.2, --gameDir, C:/Users/omerz/OneDrive/Masaüstü/MultiMC/instances/1.18.2/.minecraft, --assetsDir, C:/Users/omerz/OneDrive/Masaüstü/MultiMC/assets, --assetIndex, 1.18, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 40.2.9, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914, --width, 854, --height, 480]
[00:27:29] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 20.0.1 by Oracle Corporation
[00:27:30] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/omerz/OneDrive/Masaüstü/MultiMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2348!/ Service=ModLauncher Env=CLIENT
[00:27:32] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\omerz\OneDrive\Masaüstü\MultiMC\libraries\net\minecraftforge\fmlcore\1.18.2-40.2.9\fmlcore-1.18.2-40.2.9.jar is missing mods.toml file
[00:27:32] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\omerz\OneDrive\Masaüstü\MultiMC\libraries\net\minecraftforge\javafmllanguage\1.18.2-40.2.9\javafmllanguage-1.18.2-40.2.9.jar is missing mods.toml file
[00:27:32] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\omerz\OneDrive\Masaüstü\MultiMC\libraries\net\minecraftforge\lowcodelanguage\1.18.2-40.2.9\lowcodelanguage-1.18.2-40.2.9.jar is missing mods.toml file
[00:27:32] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\omerz\OneDrive\Masaüstü\MultiMC\libraries\net\minecraftforge\mclanguage\1.18.2-40.2.9\mclanguage-1.18.2-40.2.9.jar is missing mods.toml file
[00:27:32] [main/WARN] [ne.mi.ja.se.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: cloth_config. Using Mod File: C:\Users\omerz\OneDrive\Masaüstü\MultiMC\instances\1.18.2\.minecraft\mods\cloth-config-6.3.81-forge.jar
[00:27:32] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 31 dependencies adding them to mods collection
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.module.ResolutionException: Modules MixinExtras.beta._5 and debugify export package com.llamalad7.mixinextras to module supplementaries
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:900)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:814)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:735)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:139)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:493)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 8 more
Exiting with -1
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
MultiMC: Log upload triggered at: 09 Jul 2023 00:27:51 +0300

```

**Comment by LlamaLad7** [comment]
Not my issue, just a mod being stupid: https://github.com/murao-kun/Debugify-reforged/pull/7

**Comment by trafoziya** [comment]
Thanks!
