### ISSUE TITLE
VerifyError when using @Local

### ISSUE THREAD

**Issue by Gamebuster19901** [LlamaLad7/MixinExtras#95]
I'm not sure what is going on here. This is the mixin in question:

```java
package com.wildermods.wilderforge.mixins;

import com.llamalad7.mixinextras.sugar.Local;

import static com.wildermods.wilderforge.api.mixins.v1.Descriptor.*;
import com.wildermods.wilderforge.api.modLoadingV1.CoremodInfo;
import com.wildermods.wilderforge.launch.logging.Logger;

import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.Debug;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.asm.mixin.Unique;
import org.spongepowered.asm.mixin.injection.Slice;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;
import org.spongepowered.asm.mixin.injection.callback.LocalCapture;

import com.worldwalkergames.legacy.game.campaign.model.GameSettings;
import com.worldwalkergames.legacy.ui.menu.NewGameDialog;

@Debug(export = true)
@Mixin(value = NewGameDialog.class, remap = false)
public class NewGameDialogMixin {
	
	private static @Unique Logger LOGGER = new Logger(NewGameDialog.class);
	private @Shadow GameSettings gameSettings;
	
	@Inject(
		at = @At(
			value = "INVOKE",
			target = GDX_ARRAY + "add("+ OBJECT + ")" + VOID
		),
		slice = @Slice(
			from = @At(
				value = "INVOKE",
				target = 
				"Lcom/worldwalkergames/legacy/ui/menu/NewGameDialogData;"
				+ "getAdditionalMods()"
				+ GDX_ARRAY
			),
			to = @At("TAIL")
		),
		//locals = LocalCapture.PRINT,
		locals = LocalCapture.CAPTURE_FAILHARD,
		method = "applyGameSettings()" + VOID,
		require = 1,
		allow = 1,
		cancellable = false
	)
	/**
	 * Makes it so that all coremods are considered locked by the game's mod API
	 * 
	 * @param c
	 */
	private void onApplyGameSettings(CallbackInfo c, @Local GameSettings.ModEntry e) {
		if(e.info instanceof CoremodInfo) {
			LOGGER.info("Locking coremod " + e.modId);
			gameSettings.lockedMods.add(e.modId);
		}
	}
	
}
```

## Crash Report

```
---- WilderForge Crash Report----
//It appears I have a very minor case of serious brain damage.

Time: 2024-09-25T23:30:42.932711795Z
Description: Bad type on operand stack
Exception Details:
  Location:
    com/llamalad7/mixinextras/sugar/impl/SugarWrapperImpl.prepareHandler(Lorg/objectweb/asm/tree/MethodNode;)Lorg/objectweb/asm/tree/MethodNode; @78: invokevirtual
  Reason:
    Type 'org/spongepowered/asm/util/asm/MethodNodeEx' (current frame, stack[1]) is not assignable to 'org/objectweb/asm/MethodVisitor'
  Current Frame:
    bci: @78
    flags: { }
    locals: { 'com/llamalad7/mixinextras/sugar/impl/SugarWrapperImpl', 'org/objectweb/asm/tree/MethodNode', 'org/spongepowered/asm/mixin/extensibility/IMixinInfo', 'com/llamalad7/mixinextras/sugar/impl/handlers/HandlerInfo', 'org/spongepowered/asm/util/asm/MethodNodeEx' }
    stack: { 'org/objectweb/asm/tree/MethodNode', 'org/spongepowered/asm/util/asm/MethodNodeEx' }
  Bytecode:
    0000000: 2ab4 0030 b800 49b9 0065 0100 4d2c 2b2a
    0000010: b400 2e2a b400 2bb8 003d 4e2d c700 052b
    0000020: b0bb 0028 592b b400 322b b800 5b2b b400
    0000030: 332b b400 362b b400 3403 bd00 11b9 0063
    0000040: 0200 c000 042c b700 5a3a 042b 1904 b600
    0000050: 562b b400 372a b400 2db9 0062 0200 5719
    0000060: 042b b400 35b5 0038 1904 01b5 0039 1904
    0000070: 1206 b800 5503 b600 5c57 2d2a b400 2919
    0000080: 04b6 0048 2d2a b400 2bb6 0047 2ab4 0029
    0000090: b400 3119 04b9 0060 0200 5719 04b0     
  Stackmap Table:
    append_frame(@33,Object[#31],Object[#10])


net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of com.worldwalkergames.legacy.ui.menu.NewGameDialog failed
	at com.wildermods.provider.WildermythGameProvider.launch(WildermythGameProvider.java:389)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of com.worldwalkergames.legacy.ui.menu.NewGameDialog failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at com.worldwalkergames.legacy.ui.menu.DungeonModeProgressionPopup.createPerilAndProgressionTable(DungeonModeProgressionPopup.java:974)
	at com.worldwalkergames.legacy.game.dungeon.DungeonScreen.buildUI(DungeonScreen.java:627)
	at com.worldwalkergames.legacy.game.dungeon.DungeonScreen.update(DungeonScreen.java:753)
	at com.worldwalkergames.engine.DrivableContainer.update(DrivableContainer.java:39)
	at com.worldwalkergames.legacy.ui.LegacyUIRoot.update(LegacyUIRoot.java:754)
	at com.worldwalkergames.legacy.ui.MainScreen.update(MainScreen.java:214)
	at com.worldwalkergames.legacy.LegacyDesktop.render(LegacyDesktop.java:344)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
	at com.badlogic.gdx.backends.lwjgl3.NiceLwjgl3Application.loop(NiceLwjgl3Application.java:104)
	at com.badlogic.gdx.backends.lwjgl3.NiceLwjgl3Application.<init>(NiceLwjgl3Application.java:80)
	at com.worldwalkergames.legacy.LegacyDesktop.main(LegacyDesktop.java:151)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.wildermods.provider.WildermythGameProvider.launch(WildermythGameProvider.java:386)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 20 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinError: Error initialising injector metaclass [class com.llamalad7.mixinextras.sugar.impl.SugarWrapperInjectionInfo] for annotation Lcom/llamalad7/mixinextras/sugar/impl/SugarWrapper;
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:203)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:664)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1399)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:731)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:315)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 23 more
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/llamalad7/mixinextras/sugar/impl/SugarWrapperImpl.prepareHandler(Lorg/objectweb/asm/tree/MethodNode;)Lorg/objectweb/asm/tree/MethodNode; @78: invokevirtual
  Reason:
    Type 'org/spongepowered/asm/util/asm/MethodNodeEx' (current frame, stack[1]) is not assignable to 'org/objectweb/asm/MethodVisitor'
  Current Frame:
    bci: @78
    flags: { }
    locals: { 'com/llamalad7/mixinextras/sugar/impl/SugarWrapperImpl', 'org/objectweb/asm/tree/MethodNode', 'org/spongepowered/asm/mixin/extensibility/IMixinInfo', 'com/llamalad7/mixinextras/sugar/impl/handlers/HandlerInfo', 'org/spongepowered/asm/util/asm/MethodNodeEx' }
    stack: { 'org/objectweb/asm/tree/MethodNode', 'org/spongepowered/asm/util/asm/MethodNodeEx' }
  Bytecode:
    0000000: 2ab4 0030 b800 49b9 0065 0100 4d2c 2b2a
    0000010: b400 2e2a b400 2bb8 003d 4e2d c700 052b
    0000020: b0bb 0028 592b b400 322b b800 5b2b b400
    0000030: 332b b400 362b b400 3403 bd00 11b9 0063
    0000040: 0200 c000 042c b700 5a3a 042b 1904 b600
    0000050: 562b b400 372a b400 2db9 0062 0200 5719
    0000060: 042b b400 35b5 0038 1904 01b5 0039 1904
    0000070: 1206 b800 5503 b600 5c57 2d2a b400 2919
    0000080: 04b6 0048 2d2a b400 2bb6 0047 2ab4 0029
    0000090: b400 3119 04b9 0060 0200 5719 04b0     
  Stackmap Table:
    append_frame(@33,Object[#31],Object[#10])

	at com.llamalad7.mixinextras.sugar.impl.SugarWrapperInjectionInfo.<init>(SugarWrapperInjectionInfo.java:14)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:196)
	... 31 more

---- Additonal Information----

--System Details--
Wildermyth Version: 1.16+550 Patch
Operating System: Linux
	Architecture: amd64
	Version: 6.8.0-40-generic
Cores: 24
Memory:
	Max heap size: 7.8 GiB
	Current heap size: 628.0 MiB
	Heap used: 256.3 MiB
	Free heap: 371.7 MiB
Graphical information:
	Vendor: 
		NVIDIA Corporation
	Card: 
		NVIDIA GeForce RTX 3080/PCIe/SSE2
	Monitors:
		Total monitors (OpenGL) 2:
			Monitor 0:
				Name: DP-0
				Resolution: 3840x2160@60hz
			Monitor 1:
				Name: HDMI-0
				Resolution: 1920x1080@75hz
		Total monitors (Java): 2
			Monitor 0
				Name: :0.0
				Resolution: 5760x2160@50hz
			Monitor 1
				Name: :0.1
				Resolution: 1920x1080@0hz
Java Version: OpenJDK Runtime Environment 21.0.4+7-Ubuntu-1ubuntu222.04 
	Vendor: Ubuntu
Uptime: PT3M1.875S


-- Coremod Details --
Coremods Detected: 7:

	asm 9.0
	fabricloader 0.16.3
	java 21
	mixin 0.8.7
	mixinextras 0.4.1
	wilderforge ${WILDERFORGE_VERSION}
	wildermyth 1.16+550
```

**Comment by LlamaLad7** [comment]
You have asm on the game CL and you shouldn't

**Comment by LlamaLad7** [comment]
ME should be on the game CL and both mixin + asm should be on the parent one.
